server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
