server:
  port: 8764

spring:
  application:
    name: eureka-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8761/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: debug